---
name: Release

'on':
  push:
    tags:
      - 'v*'

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - uses: simbo/changes-between-tags-action@v1
        id: changelog
        with:
          line-prefix: '* '

      - uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ steps.changelog.outputs.tag }}
          body: |
            ## Changelog
            ${{ steps.changelog.outputs.changes }}
            #### Previous Release: ${{ steps.changelog.outputs.ref }}
          make_latest: true
